### sigmoid_cross_entropy_with_logits 用法

In [96]:
import tensorflow as tf
_logits = [[0.5, 0.7, 0.3], [0.8, 0.2, 0.9]]
_one_labels = tf.ones_like(_logits)
_zero_labels = tf.zeros_like(_logits)

with tf.Session() as sess:
    print(sess.run(_one_labels))
    print(sess.run(_zero_labels))

    loss = tf.nn.sigmoid_cross_entropy_with_logits(logits=_logits, labels=_one_labels)
    print(sess.run(loss))
    print(sess.run(tf.reduce_mean(loss)))
    # [[0.47407699  0.40318602  0.5543552]   
    #  [0.37110069  0.59813887  0.34115386]]  
    
    loss = tf.nn.sigmoid_cross_entropy_with_logits(logits=_logits, labels=_zero_labels)
    print(sess.run(loss))
    # [[0.97407699  1.10318601  0.85435522]   
    #  [1.17110074  0.79813886  1.24115384]]

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0.474077   0.40318605 0.55435526]
 [0.37110066 0.59813887 0.34115386]]
0.45700195
[[0.974077   1.103186   0.8543553 ]
 [1.1711006  0.79813886 1.2411538 ]]


### mean_squared_error 用法

In [36]:
import tensorflow as tf
import pandas as pd
pred = [1,2,3,4]
pred = pd.Series(pred)
label = [1.1, 2.1, 3.2, 9.3]
label = [1,2,3,4]
label = pd.Series(label)
with tf.Session() as ss:
    print(ss.run(tf.losses.mean_squared_error(label, pred)))

ValueError: Argument must be a dense tensor: 0    1
1    2
2    3
3    4
dtype: int64 - got shape [4], but wanted [].